### ISSUE TITLE
Failing to build with GCC 7.2.1

### ISSUE THREAD

**Issue by yaabdalla** [ishovkun/SierraBreeze#6]
```
`[  5%] Automatic MOC for target sierrabreeze
AutoMoc warning:
  "/home/nimbus/SierraBreeze/breezedecoration.cpp"
The file includes the moc file "breezedecoration.moc", but does not contain a Q_OBJECT, Q_GADGET or Q_NAMESPACE macro.

[  5%] Built target sierrabreeze_autogen
[ 10%] Building CXX object CMakeFiles/sierrabreeze.dir/breezesizegrip.cpp.o
In file included from /usr/include/qt/QtWidgets/QWidget:1:0,
                 from /home/nimbus/SierraBreeze/breezesizegrip.h:28,
                 from /home/nimbus/SierraBreeze/breezesizegrip.cpp:21:
/usr/include/qt/QtWidgets/qwidget.h:186:14: error: missing binary operator before token "("
 #if QT_CONFIG(statustip)
              ^
/usr/include/qt/QtWidgets/qwidget.h:189:14: error: missing binary operator before token "("
 #if QT_CONFIG(whatsthis)
              ^
/usr/include/qt/QtWidgets/qwidget.h:350:14: error: missing binary operator before token "("
 #if QT_CONFIG(graphicseffect)
              ^
/usr/include/qt/QtWidgets/qwidget.h:389:14: error: missing binary operator before token "("
 #if QT_CONFIG(statustip)
              ^
/usr/include/qt/QtWidgets/qwidget.h:393:14: error: missing binary operator before token "("
 #if QT_CONFIG(whatsthis)
              ^
/usr/include/qt/QtWidgets/qwidget.h:454:14: error: missing binary operator before token "("
 #if QT_CONFIG(graphicsview)
              ^
/usr/include/qt/QtWidgets/qwidget.h:616:14: error: missing binary operator before token "("
 #if QT_CONFIG(wheelevent)
              ^
/usr/include/qt/QtWidgets/qwidget.h:632:14: error: missing binary operator before token "("
 #if QT_CONFIG(tabletevent)
              ^
/usr/include/qt/QtWidgets/qwidget.h: In member function ‘void QWidget::setTabletTracking(bool)’:
/usr/include/qt/QtWidgets/qwidget.h:817:20: error: ‘WA_TabletTracking’ is not a member of ‘Qt’
 { setAttribute(Qt::WA_TabletTracking, enable); }
                    ^~~~~~~~~~~~~~~~~
/usr/include/qt/QtWidgets/qwidget.h:817:20: note: suggested alternative: ‘WA_MouseTracking’
 { setAttribute(Qt::WA_TabletTracking, enable); }
                    ^~~~~~~~~~~~~~~~~
                    WA_MouseTracking
/usr/include/qt/QtWidgets/qwidget.h: In member function ‘bool QWidget::hasTabletTracking() const’:
/usr/include/qt/QtWidgets/qwidget.h:820:28: error: ‘WA_TabletTracking’ is not a member of ‘Qt’
 { return testAttribute(Qt::WA_TabletTracking); }
                            ^~~~~~~~~~~~~~~~~
/usr/include/qt/QtWidgets/qwidget.h:820:28: note: suggested alternative: ‘WA_MouseTracking’
 { return testAttribute(Qt::WA_TabletTracking); }
                            ^~~~~~~~~~~~~~~~~
                            WA_MouseTracking
make[2]: *** [CMakeFiles/sierrabreeze.dir/build.make:183: CMakeFiles/sierrabreeze.dir/breezesizegrip.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:388: CMakeFiles/sierrabreeze.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
```

**Comment by ishovkun** [comment]
Have you tried building Breeze sources?

**Comment by yaabdalla** [comment]
Yeah, it also fails to build. Same messages. On Manjaro, if that helps.

**Comment by ishovkun** [comment]
I guess you are missing some libraries.
Try to find the analogue of the prerequisites listed in readme for Ubuntu.

**Comment by omni6** [comment]
Succesfully built in clean chroot with [PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=sierrabreeze-kwin-decoration-git). I dont't think that this is a dependency issue.

Here my [buildlog](https://pastebin.com/raw/VPLZ9htH)

**Comment by yaabdalla** [comment]
Yeah, I don't think this is a dependency issue either. I have all the dependencies installed and up to date.

**Comment by ishovkun** [comment]
Sorry man, I wish I could help you but I have no idea how. The file breezedecoration.cpp is completely identical to that from breeze (except the namespace name). Since you cannot build breeze, I suggest you search help from kde devs.

**Comment by omni6** [comment]
@yaabdalla 
maybe the source got corrupted? I see you are building in your homedir in a non temorarily directory. maybe you should clean everything and try sometging like:

`mkdir sierrabreeze && cd sierrabreeze && curl https://aur.archlinux.org/cgit/aur.git/plain/PKGBUILD?h=sierrabreeze-kwin-decoration-git > PKGBUILD && makepkg -csri`
